pipeline {
  agent any
  
  stages {

    stage('Compile') { 
      steps {
        if (isUnix()) {
	      sh 'mvn --batch-mode clean compile'
	    } else {
	      bat 'mvn --batch-mode clean compile'
	    }
      }
    }

    stage('Verify') { 
      steps {
        if (isUnix()) {
	      sh 'mvn --batch-mode verify'
	    } else {
	      bat 'mvn --batch-mode verify'
	    }
      }
    }

    stage('Install') { 
      steps {
        if (isUnix()) {
	      sh 'mvn --batch-mode install'
	    } else {
	      bat 'mvn --batch-mode install'
	    }
      }
    }
  }
}