pipeline {
  agent any
  
  stages {

    stage('Compile') { 
      steps {
        execute('mvn --batch-mode clean compile')
      }
    }

    stage('Verify') { 
      steps {
        execute('mvn --batch-mode verify')
      }
    }

    stage('Install') { 
      steps {
        execute('mvn --batch-mode install')
      }
    }
  }
}

def execute(cmd) {
  if (Boolean.valueOf(env.UNIX)) {
    sh cmd
  } else {
    bat cmd
  }
}