pipeline {
  agent any
  
  stages {

    stage('Compile') { 
      steps {
		dir('iso_demo') {
          execute('mvn --batch-mode clean compile')
        }
      }
    }

    stage('Verify') { 
      steps {
		dir('iso_demo') {
          execute('mvn --batch-mode verify')
        }
      }
    }

    stage('Install') { 
      steps {
		dir('iso_demo') {
          execute('mvn --batch-mode install')
        }
      }
    }
  }
}

def execute(cmd) {
  if (Boolean.valueOf(env.UNIX)) {
    sh cmd
  } else {
    bat cmd
  }
}